### ISSUE TITLE
Potential wrong version selection for dflydev/dot-access-configuration

### ISSUE THREAD

**Issue by greg-1-anderson** [hechoendrupal/drupal-console-core#143]
Drupal Console currently requests:
```
"dflydev/dot-access-configuration": "~1.0",
```
This explicitly excludes v1.1. Perhaps "^1.0" or "~1" was intended -- unless 1.1.0 specifically breaks Drupal Console. I have not tested this release.

c.f. #123

**Comment by jmolivas** [comment]
I have not tested `1.1.0` I will give a try and then update the dependency

**Comment by gapple** [comment]
`acquia/blt` started requiring `dflydev/dot-access-data: ^1.1.0` as of `8.7.0`, which causes a conflict.  As a result, older BLT projects that include Drupal Console are unable to update BLT, and newer BLT projects are unable to install Drupal Console.

**Comment by jmolivas** [comment]
Fixed with https://github.com/hechoendrupal/drupal-console-core/pull/197

**Comment by gapple** [comment]
Thanks, I was just able to verify that adding `drupal/console` as a dependency of a new 8.9.0 `acquia/blt` project works without conflict.

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by jmolivas** [comment]
thanks @gapple for testing and @greg-1-anderson for reporting.
