### ISSUE TITLE
Allow usage of symfony components "^2.7|^3.0"

### ISSUE THREAD

**Issue by robertfausk** [hechoendrupal/drupal-console-core#151]
Currently it's ```>=2.7 <3.0``` prevents install and usage of composer packages which requires e.g. ```symfony/yaml ^3.1```

**Comment by jmolivas** [comment]
@robertfausk symfony components are no longer required by the Launcher.

**Comment by jmolivas** [comment]
My bad @robertfausk  I was thinking in another repository this is is still open and something we need to check.

**Comment by Chi-teck** [comment]
It also makes Drupal Console incompatible with Drupal 8.4.
https://github.com/hechoendrupal/drupal-console/issues/2987

**Comment by jmolivas** [comment]
I will test updating dependencies to make sure changes doe not introduce bugs in this project `drupal/console-core` and also `drupal/console`.

**Comment by aguasingas** [comment]
Hi, @jmolivas! Any progress on this issue? Is there any way I could help?
