### ISSUE TITLE
InitCommand should create sites folder by default

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/drupal-console-core#220]
The command `drupal -n --override init` creates _~/.console_ folder
it also creates  _~/.console/chain_.
It does not copy the example files, which is fair enough, but it does create the chain folder.

When you try to run any command without sites folder, it shows this error:

> You must call one of in() or append() methods before iterating over a Finder

I am proposing this command creates _~/.console/sites_, but not copy site examples, same way it happens to chain _folder_.
Also, we should have a more friendly message, i.e. 

> Could not find any site on ~/.console/sites folder

**Comment by jmolivas** [comment]
@marcelovani Fixed with PR https://github.com/hechoendrupal/drupal-console-core/pull/231
