### ISSUE TITLE
Help text is not replaced with translated value

### ISSUE THREAD

**Issue by LOBsTerr** [hechoendrupal/drupal-console-core#261]
### Problem
When we run any command with --help param we don't see the real help message, we see translation string. For exmaple
`
drupal list --help
`
Result
`
...
Help:
 commands.list.help
`

### Solution
Handle the help the same way we handle the description of the command. We need to override **getHelp** method in order to get translated value.

**Comment by LOBsTerr** [comment]
I have fixed it in this PR: https://github.com/hechoendrupal/drupal-console-core/pull/262

**Comment by jmolivas** [comment]
PR: #262 mrged
Closing this one. Feel free to re-open if still happening after updating to the latest version.
