### ISSUE TITLE
BC break, PHP 5.6 compatibility

### ISSUE THREAD

**Issue by webflo** [hechoendrupal/drupal-console-core#276]
Not sure if PHP 5.6 compatibility is a goal. https://github.com/hechoendrupal/drupal-console-core/pull/267 broke it because the second parameter for ``dirname`` is PHP 7 only.

http://php.net/manual/en/function.dirname.php

**Comment by webflo** [comment]
Closing. @Sacrileigous was faster :) 👍

**Comment by webflo** [comment]
https://github.com/hechoendrupal/drupal-console-core/issues/274

**Comment by jmolivas** [comment]
@webflo This should be fixed on 1.5.0 could you update to latest version and confirm.
