### ISSUE TITLE
Backward compatibility for legacy variable placeholders

### ISSUE THREAD

**Issue by marcelovani** [hechoendrupal/drupal-console-core#286]
On this commit https://github.com/hechoendrupal/drupal-console-core/commit/83cc1a46cbc26c59505241b6e0896532597bebe1 we changed the way the inline and environment placeholders were defined.

I am proposing we add some code to:

- Allow the legacy format to be recognized
- Display a message to let the user know that the chain files need to be updated

**Comment by marcelovani** [comment]
PR here https://github.com/hechoendrupal/drupal-console-core/pull/287/files

**Comment by jmolivas** [comment]
Fixed  with PR https://github.com/hechoendrupal/drupal-console-core/pull/297

**Comment by jmolivas** [comment]
This is how the message looks like:

 ![](https://monosnap.com/file/w0srfLgV7jCGORlk1TH7IhVSs3Jizg.png)

**Comment by jmolivas** [comment]
This improvement was included on 1.6.0
