### ISSUE TITLE
Fatal error on PHP 5.5.9 related to constant arrays

### ISSUE THREAD

**Issue by wluijt-endertech** [hechoendrupal/drupal-console-core#318]
After executing `composer update` in my Drupal 8 project, the `drupal/console-core` was updated from 1.5.0 to 1.6.0.  When executing `vendor/bin/drupal cr`, I see the following error in the command line:

> Fatal error: Arrays are not allowed in class constants in vendor/drupal/console-core/src/Utils/ChainDiscovery.php on line 60

I am running a system with PHP 5.5.9, which seems to be the oldest supported PHP in the Drupal 8 Core composer.json file.

**Comment by jmolivas** [comment]
This PR https://github.com/hechoendrupal/drupal-console-core/pull/319 should fix the issue.

**Comment by jmolivas** [comment]
Fixed included on 1.6.1
Closing this one. Feel free to re-open if still happening after updating to the latest version.
