### ISSUE TITLE
Support for symfony/debug v4 due to conflict with Drush

### ISSUE THREAD

**Issue by kenorb** [hechoendrupal/drupal-console-core#338]
Currently, I've got `symfony/debug` `v4.0.6` installed as per:

```
$ composer global why symfony/debug -t
symfony/debug v4.0.6 Symfony Debug Component
└──symfony/console v3.4.6 (requires symfony/debug ~2.8|~3.0|~4.0)
   ├──consolidation/annotated-command 2.8.3 (requires symfony/console ^2.8|^3|^4)
   │  └──drush/drush 8.1.16 (requires consolidation/annotated-command ^2.8.1)
   │     └──__root__ (requires drush/drush ~8@stable)
   ├──consolidation/output-formatters 3.2.0 (requires symfony/console ^2.8|^3|^4)
   │  ├──consolidation/annotated-command 2.8.3 (requires consolidation/output-formatters ^3.1.12)
   │  │  └──drush/drush 8.1.16 (requires consolidation/annotated-command ^2.8.1)
   │  │     └──__root__ (requires drush/drush ~8@stable)
   │  └──drush/drush 8.1.16 (requires consolidation/output-formatters ~3)
   │     └──__root__ (requires drush/drush ~8@stable)
   ├──drush/drush 8.1.16 (requires symfony/console ~2.7|^3)
   │  └──__root__ (requires drush/drush ~8@stable)
   └──psy/psysh v0.8.17 (requires symfony/console ~2.3.10|^2.4.2|~3.0|~4.0)
      └──drush/drush 8.1.16 (requires psy/psysh ~0.6)
         └──__root__ (requires drush/drush ~8@stable)
```

So I cannot install the latest version of [`drupal/console`](https://github.com/hechoendrupal/drupal-console) (v1.8) since `drupal/console-core` requires `symfony/debug` `~2.8|~3.0` (but not `~4.0`).

```
$ composer global show -a drupal/console-core | grep debug
symfony/debug ~2.8|~3.0
```

Is there any chance to expand the dependencies to support `symfony/debug` as `~2.8|~3.0|~4.0`? Or drop it from the `composer.json`, since `symfony/debug` is already included with `symfony/console 3.4.6`, e.g.

```
$ composer global show -a symfony/console 3.4.6 | grep debug
symfony/debug ~2.8|~3.0|~4.0
```

----

My error:

```
$ composer global require drupal/console
  Problem 1
    - drupal/console 1.8.0 requires drupal/console-core 1.8.0 -> satisfiable by drupal/console-core[1.8.0].
    - Installation request for drupal/console ^1.8 -> satisfiable by drupal/console[1.8.0].
    - Conclusion: remove symfony/debug v4.0.6
    - Conclusion: don't install symfony/debug v4.0.6
    - drupal/console-core 1.8.0 requires symfony/debug ~2.8|~3.0 -> satisfiable by symfony/debug
...
    - Can only install one of: symfony/debug[v3.4.6, v4.0.6].
    - Installation request for symfony/debug (locked at v4.0.6) -> satisfiable by symfony/debug[v4.0.6].
```

My existing `composer.json`:

```
{
    "require": {
        "drush/drush": "~8@stable"
    }
}
```

**Comment by Helrunar** [comment]
I have the same error. Switched back to symfony/debug 3.4.8 to get drupal/console installed

**Comment by mikecrittenden** [comment]
Bumping this issue. Is there any particular reason why v4 of symfony/debug isn't allowed?

**Comment by sealionking** [comment]
the same issue and the following solved the problem

> I had to do the following to install the drupal console:
> `composer require symfony/debug:3.4.8`
> `composer require symfony/dom-crawler:3.4.9`
> `composer require --dev drupal/console`

**Comment by greggles** [comment]
I had this problem on a site that did not have Drush installed, so that part of the title is misleading.

I noted that all the other packages that rely on symfony/debug support older versions as well, so the solutions posted here of requiring a 3.x version of symfony/debug worked for me as well. I also filed a [pull request 347](https://github.com/hechoendrupal/drupal-console-core/pull/347) to address this. I didn't test it. I assumed there was some automated tests, but it seems that's not the case.

**Comment by benk-cogapp** [comment]
I believe this is now causing incompatibility with Drupal 9 due to the `~2.8|~3.0` version requirements, as in D9 all Symfony dependencies are pinned to be `^4.4`. Can we have a version released to support these same Symfony dependencies? Thanks.

**Comment by LOBsTerr** [comment]
We can close the ticket, because "symfony/debug": "~3.0|^4.4" is supported
