### ISSUE TITLE
Infinite loop with latest composer/installers

### ISSUE THREAD

**Issue by eiriksm** [hechoendrupal/drupal-console-core#363]
Easy to reproduce, see: https://github.com/drupal-composer/drupal-project/issues/508

Basically I would suggest 2 changes:

- Try to avoid recursive function call if buildCoreLanguageDirectory is called with language `en`. Rather throw an exception.
- Support both locations for language directory

**Comment by zrhoffman** [comment]
Fix is in PR hechoendrupal/drupal-console-core#364 (thanks @eiriksm!)
