### ISSUE TITLE
[develop-contribute] [feature-request] it should download & install the mandatory modules for translating

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console-core#370]
`develop-contribute` command should download and install the following modules, which are mandatory for translating:

        - rest
        - taxonomy
        - locale
        - migrate
        - simpletest
        - breakpoint
        - node
        - views
        - features

these modules were enabled in the past by `update-gitbook.yml` chain file, but gitbook repo is obsolete now

**Comment by novia713** [comment]
PR for this at https://github.com/hechoendrupal/drupal-console-core/pull/371

**Comment by enzolutions** [comment]
Merged
