### ISSUE TITLE
update Twig for _site:new_ command in order to avoid some Twig errors

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console-core#381]
having in consideration these errrors i've updated the composer.json to the latest version
![Captura de pantalla 2020-05-28 a las 9 44 04](https://user-images.githubusercontent.com/423279/83180841-4e228080-a124-11ea-9d5e-dff2c2cb878b.jpg)

i've tested some commands and it seems to work fine :-)

**Comment by novia713** [comment]
see PR https://github.com/hechoendrupal/drupal-console-core/pull/382

**Comment by novia713** [comment]
see PR at https://github.com/hechoendrupal/drupal-console-core/pull/382

**Comment by novia713** [comment]
@jmolivas regarding the new recommended repo for installing a site, see the PR attached at https://github.com/hechoendrupal/drupal-console-core/issues/373

**Comment by LOBsTerr** [comment]
Merged, thank you for contribution
